Tut = [
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOWWWWWWWOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOW       WOOOOOOOOOOWWWOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOW       WWWWWWWWWWW   WOOOOOOOOOOOOOOOOOOOOOOO',       #The level grids are 50x40
    'OOOOW  P                   WOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOW                      WOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOW       WWWWWWWWWWW   WOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOW       WOOOOOOOOOW E WOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOWWWWWWWOOOOOOOOOOOWWWOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO'
]

LevelOne = [
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OP W WWWWW     WWW     WWW     WWW     WWW     WWO',
    'O W      W             W W     W W       W     W O',
    'O WWWWW WW     WWW     W W     W W     W W     WWO',
    'O         W   W   W   W   W   W   W   W   W   W  O',
    'O WWWW WWWWWWW     W W     WWW     WWW     WWW   O',
    'O W      WW  W             W       W         W   O',
    'O WWWWWWW WWWW     WWW     W W     W W     W W   O',
    'O             W   W   W   W   W   W   W   W   W  O',
    'O WWW WWWWWWWWWWWW     W W     WWW     WWW     WWO',
    'OWWWW W          W       W       W       W       O',
    'O   W WW WW WWWWWW     W W     W W     W W     WWO',
    'O W W     W       W   W   W   W   W   W   W   W  O',
    'O WWWWWW WW WWW WWWWWW     W W     WWW     W W   O',
    'O        WW W        W       W       W     W W   O',
    'OWWWWW WWWW WWW WWWWWW     W W     W W     W W   O',
    'O      WW W W   W    WW   W   W   W   W   W   W  O',
    'OWWWWWWW    W  W  WW W W W     WWW     W W     WWO',
    'O          WW W  W W W W W       W       W       O',
    'OWWW WW WWWW    WWWW W W W     W W     WWW     W O',
    'O    W   W  W  W   WWW W  W   W   W   W   W   W  O',
    'OWW WW  W  W  W  W      W  WWW     W W     W W   O',
    'O   W  W  W  W  W  WWW   W   W     W W       W   O',
    'O WW  W  W  W  W     W    W  W     W W     W W   O',
    'O W  W  W  W  W   WWWWWWWWW   W   W   W   W   W  O',
    'O W W  W  W  W    W            WWW     WWW     W O',
    'O W   W  W  W     W WWWWWWWWW    W     W       W O',
    'O WWWW  W  W      W         WW   W     W W     W O',
    'O W    W  WWWWWW WWWW WWWWW W W   W   W   W   W  O',
    'OWW   W  W       W       WW W W    WWW     WWW   O',
    'O W  W  WW       W WWWWWW W W W W    W       W   O',
    'OW  W  W W       W        W W W WWWW W     W W   O',
    'O  W  W      W   WWWW WWWWWWW W WW W  W   W   W  O',
    'O W  WWWWW       W  W W   W W W WW WW  WWW     W O',
    'O   W    W       W  W W W W W W WW W W W W     W O',
    'O  W   WWW       W  W   W   W W WW W W W W     W O',
    'O W   W  W WWWWWWW  W W W W W   WW W W    W   W  O',
    'O W  W   W W        W W W W WWWWWW W W WWWWWWW   O',
    'O   W    W            W   W          W W     W  EO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO'
]

LevelTwo = [
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OE                                               O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                       W W                      O',
    'O                      WW WW                     O',
    'O                                                O',
    'O                      WW WW                     O',
    'O                       W W                      O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                              P O',
    'O                                                O',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO'

]


LevelThree = [
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'O                                                O',
    'O P                                              O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                                O',
    'O                                               EO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO'
]
Levelslist = [Tut, LevelOne, LevelTwo, LevelThree]
LevelsCount = len(Levelslist)